# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zacklacanna.dev
title: Zack LaCanna
email: zacklacanna23@gmail.com
author: Zack LaCanna
description: >  
  Here you can see previous projects I have contributed on over the course of my Computer Science journey.
  
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/zacklacanna
  - title: linkedin
    url: https://linkedin.com/in/zacklacanna
